name: ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain: ["stable", "minimum"]
    name: Rust Tests (${{ matrix.rust-toolchain }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: cargo check
        run: nix develop .#rust-${{ matrix.rust-toolchain }} --command cargo check
      - name: cargo build
        run: nix develop .#rust-${{ matrix.rust-toolchain }} --command cargo build
      - name: cargo test
        run: nix develop .#rust-${{ matrix.rust-toolchain }} --command cargo test

  cargo-fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain: ["stable"]
    name: Rust Formatting (${{ matrix.rust-toolchain }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Run cargo fmt
        run: nix develop .#rust-${{ matrix.rust-toolchain }} --command cargo fmt

  cargo-clippy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain: ["stable"]
    name: Clippy (${{ matrix.rust-toolchain }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      # This is a workaround for https://github.com/oxalica/rust-overlay/issues/54,
      # avoiding link errors when running cargo commands with `nix develop`.
      - name: Remove binaries installed in ~/.cargo/bin
        run: rm --recursive --force --verbose ~/.cargo/bin

      - name: Run cargo clippy
        run: nix develop .#rust-${{ matrix.rust-toolchain }} --command cargo clippy -- --deny warnings

  nixpkgs-fmt:
    runs-on: ubuntu-latest
    name: Nix Formatting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17

      - name: Run nixpkgs-fmt
        run: nix develop .#nix --command nixpkgs-fmt --check .
